# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20170718_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('use', models.BooleanField()),
                ('course', models.CharField(max_length=8, null=True)),
                ('picture', models.ImageField(default='items/default_item.jpg', upload_to='items/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('numRaters', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
