# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170718_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='use',
            field=models.IntegerField(default=0),
        ),
    ]
