# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_type'),
        ('posts', '0005_auto_20170726_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerCash', models.PositiveIntegerField(default=0)),
                ('message', models.TextField()),
                ('offerFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('offerPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerPost', to='posts.Post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.Post')),
            ],
        ),
    ]
