# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date_offered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
