# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_offer_date_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerPost', to='posts.Post'),
        ),
    ]
