# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170814_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerPost', to='posts.Post'),
        ),
    ]
