# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170814_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
