# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170718_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Faculty Member')], default=0),
        ),
    ]
